let products = [
	{
		id: 1001,
		title: "Cat Food, 25lb bag",
		description: "A 25 pound bag of <em>irresistible</em>, organic goodness for your cat.",
		price: 60,
		image: "img/product1.gif",
		availableInventory: 10,
		rating: 3,
	},
	{
		id: 1002,
		title: "Dog Food, 30lb bag",
		description: "A 30 pound bag of premium, grain-free kibble for your dog.",
		price: 85,
		image: "img/product2.jpg",
		availableInventory: 15,
		rating: 4,
	},
	{
		id: 1003,
		title: "Bird Seed, 5lb bag",
		description: "A 5 pound bag of nutrient-rich seeds, perfect for all bird species.",
		price: 20,
		image: "img/product3.jpg",
		availableInventory: 25,
		rating: 5,
	},
	{
		id: 1004,
		title: "Cat Toy - Feather Wand",
		description: "An interactive feather wand toy to keep your cat entertained.",
		price: 9,
		image: "img/product4.jpg",
		availableInventory: 30,
		rating: 4,
	},
	{
		id: 1005,
		title: "Dog Leash, 6ft",
		description: "A durable 6-foot leash for walking your dog.",
		price: 15,
		image: "img/product5.jpg",
		availableInventory: 15,
		rating: 4,
	},
	{
		id: 1006,
		title: "Fish Tank, 20-gallon",
		description: "A 20-gallon aquarium for freshwater fish, with built-in filter.",
		price: 150,
		image: "img/product6.jpg",
		availableInventory: 6,
		rating: 5,
	},
	{
		id: 1007,
		title: "Hamster Wheel, Silent",
		description: "A quiet, sturdy exercise wheel for your hamster.",
		price: 15,
		image: "img/product7.jpg",
		availableInventory: 20,
		rating: 4,
	},
];
