let products = [
    {
        id: 1001,
        title: "Cat Food, 25lb bag",
        description: "A 25 pound bag of <em>irresistible</em>, organic goodness for your cat.",
        price: 2000,
        image: "img/product1.gif",
        availableInventory: 10,
        displayedInventory: 10,
    },
    {
        id: 1002,
        title: "Dog Food, 30lb bag",
        description: "A 30 pound bag of premium, grain-free kibble for your dog.",
        price: 2500,
        image: "img/product2.gif",
        availableInventory: 15,
        displayedInventory: 15,
    },
    {
        id: 1003,
        title: "Bird Seed, 5lb bag",
        description: "A 5 pound bag of nutrient-rich seeds, perfect for all bird species.",
        price: 800,
        image: "img/product3.gif",
        availableInventory: 25,
        displayedInventory: 25,
    },
    {
        id: 1004,
        title: "Cat Toy - Feather Wand",
        description: "An interactive feather wand toy to keep your cat entertained.",
        price: 500,
        image: "img/product4.gif",
        availableInventory: 50,
        displayedInventory: 50,
    },
    {
        id: 1005,
        title: "Dog Leash, 6ft",
        description: "A durable 6-foot leash for walking your dog.",
        price: 1200,
        image: "img/product5.gif",
        availableInventory: 20,
        displayedInventory: 20,
    },
    {
        id: 1006,
        title: "Fish Tank, 20-gallon",
        description: "A 20-gallon aquarium for freshwater fish, with built-in filter.",
        price: 5000,
        image: "img/product6.gif",
        availableInventory: 8,
        displayedInventory: 8,
    },
    {
        id: 1007,
        title: "Hamster Wheel, Silent",
        description: "A quiet, sturdy exercise wheel for your hamster.",
        price: 900,
        image: "img/product7.gif",
        availableInventory: 30,
        displayedInventory: 30,
    },
];
